import { useId, useState } from 'react';
import { Link } from 'react-router-dom';
import {
  ArrowLeft,
  CheckCircle2,
  ChevronRight,
  Cylinder,
  SquarePen,
  type LucideIcon,
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Diamond } from '@/components/brand/Diamond';
import { toast } from '@/components/ui/sonner';
import { ApiError } from '@/lib/api/client';
import { useCaseFilesQuery, useCreateCaseFile, useSaveCaseFile } from '@/features/projects/useCaseFiles';

/**
 * TopoSetDialog - a project tool (opened from the Case files toolbar) that
 * writes `system/topoSetDict`, the dictionary `topoSet` reads to build named
 * cell sets / zones (e.g. the rotor cellZone a Frozen Rotor or Moving Rotor
 * setup references - see BoundaryConditionDialog's rotor step). It never runs
 * `topoSet` itself: that stays a manual step on the OpenFOAM server, same as
 * the existing rotor-zone warning already says.
 *
 * Two modes:
 *  - Basic: a small cylinder form (cell zone name + two axis points + radius)
 *    generates a ready `cylinderToCell` + `setToCellZone` action pair.
 *  - Manual: creates the file with a commented starter skeleton (if it
 *    doesn't exist yet) and hands off to the existing file editor.
 */

const TOPOSET_PATH = 'system/topoSetDict';

type Mode = 'basic' | 'manual';
type Step = 'mode' | 'cylinder' | 'done';

/** Standard OpenFOAM dictionary banner, matching the app's other generated files. */
function foamBanner(object: string, location: string): string {
  return `/*--------------------------------*- C++ -*----------------------------------*\\
| =========                 |                                                 |
| \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\\\    /   O peration     | Generated by DIVE Turbinen (TopoSet helper)     |
|   \\\\  /    A nd           |                                                 |
|    \\\\/     M anipulation  |                                                 |
\\*---------------------------------------------------------------------------*/
FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    location    "${location}";
    object      ${object};
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
`;
}

const FOAM_FOOTER = '\n// ************************************************************************* //\n';

interface CylinderParams {
  cellZone: string;
  p1: [string, string, string];
  p2: [string, string, string];
  radius: string;
}

/** Build a topoSetDict defining a cylindrical cellSet, then promoting it to a cellZone. */
function buildTopoSetDict({ cellZone, p1, p2, radius }: CylinderParams): string {
  const zone = cellZone.trim() || 'rotor';
  const cellSetName = `${zone}Cells`;
  return `${foamBanner('topoSetDict', 'system')}
actions
(
    {
        name    ${cellSetName};
        type    cellSet;
        action  new;
        source  cylinderToCell;
        sourceInfo
        {
            p1     (${p1.join(' ')});
            p2     (${p2.join(' ')});
            radius ${radius || '0.5'};
        }
    }
    {
        name    ${zone};
        type    cellZoneSet;
        action  new;
        source  setToCellZone;
        sourceInfo
        {
            set     ${cellSetName};
        }
    }
);
${FOAM_FOOTER}`;
}

/** A commented starter skeleton for hand-written topoSet actions. */
function buildManualTopoSetTemplate(): string {
  return `${foamBanner('topoSetDict', 'system')}
// Add the actions that build your sets / zones below. Example: a cylindrical
// cell zone (the same pattern the "Basic" mode generates):
//
// actions
// (
//     {
//         name    rotorCells;
//         type    cellSet;
//         action  new;
//         source  cylinderToCell;
//         sourceInfo
//         {
//             p1     (0 0 -0.1);
//             p2     (0 0 0.1);
//             radius 0.5;
//         }
//     }
//     {
//         name    rotor;
//         type    cellZoneSet;
//         action  new;
//         source  setToCellZone;
//         sourceInfo
//         {
//             set     rotorCells;
//         }
//     }
// );

actions
(
);
${FOAM_FOOTER}`;
}

export function TopoSetDialog({
  projectId,
  open,
  onOpenChange,
}: {
  projectId: string;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}) {
  const [step, setStep] = useState<Step>('mode');
  const [mode, setMode] = useState<Mode | null>(null);
  const [cellZone, setCellZone] = useState('rotor');
  const [p1, setP1] = useState<[string, string, string]>(['0', '0', '-0.1']);
  const [p2, setP2] = useState<[string, string, string]>(['0', '0', '0.1']);
  const [radius, setRadius] = useState('0.5');
  const [busy, setBusy] = useState(false);
  const [resultMode, setResultMode] = useState<Mode | null>(null);

  const { data: entries } = useCaseFilesQuery(projectId);
  const fileExists = !!entries?.some(
    (entry) => entry.type === 'file' && entry.path === TOPOSET_PATH,
  );

  const create = useCreateCaseFile(projectId);
  const save = useSaveCaseFile(projectId);

  const writeDict = async (content: string) => {
    if (fileExists) {
      await save.mutateAsync({ path: TOPOSET_PATH, content });
    } else {
      await create.mutateAsync({ path: TOPOSET_PATH, content });
    }
  };

  const handleCreateBasic = async () => {
    setBusy(true);
    try {
      await writeDict(buildTopoSetDict({ cellZone, p1, p2, radius }));
      toast.success(`Wrote ${TOPOSET_PATH} (cell zone "${cellZone.trim() || 'rotor'}").`);
      setResultMode('basic');
      setStep('done');
    } catch (err) {
      toast.error(err instanceof ApiError ? err.message : 'Could not write the file.');
    } finally {
      setBusy(false);
    }
  };

  const handleManual = async () => {
    if (fileExists) {
      setResultMode('manual');
      setStep('done');
      return;
    }
    setBusy(true);
    try {
      await create.mutateAsync({ path: TOPOSET_PATH, content: buildManualTopoSetTemplate() });
      toast.success(`Created ${TOPOSET_PATH} with a starter template.`);
      setResultMode('manual');
      setStep('done');
    } catch (err) {
      toast.error(err instanceof ApiError ? err.message : 'Could not create the file.');
    } finally {
      setBusy(false);
    }
  };

  const continueFromMode = () => {
    if (mode === 'basic') {
      setStep('cylinder');
    } else if (mode === 'manual') {
      void handleManual();
    }
  };

  const radiusValid = Number.parseFloat(radius) > 0;
  const cylinderReady = cellZone.trim().length > 0 && radiusValid;

  return (
    <Dialog open={open} onOpenChange={(next) => !busy && onOpenChange(next)}>
      {step === 'mode' && (
        <ModeStep
          mode={mode}
          onPick={setMode}
          busy={busy && mode === 'manual'}
          onContinue={continueFromMode}
          onCancel={() => onOpenChange(false)}
        />
      )}

      {step === 'cylinder' && (
        <CylinderStep
          cellZone={cellZone}
          p1={p1}
          p2={p2}
          radius={radius}
          fileExists={fileExists}
          ready={cylinderReady}
          busy={busy}
          onCellZoneChange={setCellZone}
          onP1Change={setP1}
          onP2Change={setP2}
          onRadiusChange={setRadius}
          onBack={() => setStep('mode')}
          onCreate={() => void handleCreateBasic()}
        />
      )}

      {step === 'done' && resultMode && (
        <DoneStep
          projectId={projectId}
          mode={resultMode}
          onAdjust={() => setStep(resultMode === 'basic' ? 'cylinder' : 'mode')}
          onClose={() => onOpenChange(false)}
        />
      )}
    </Dialog>
  );
}

/** A selectable card wrapping a native radio (matches BoundaryConditionDialog's OptionCard). */
function OptionCard({
  name,
  value,
  checked,
  icon: Icon,
  label,
  description,
  onSelect,
}: {
  name: string;
  value: string;
  checked: boolean;
  icon: LucideIcon;
  label: string;
  description: string;
  onSelect: () => void;
}) {
  return (
    <label
      className={cn(
        'relative flex cursor-pointer items-start gap-3 rounded-md border p-3 transition-colors duration-fast ease-out',
        'focus-within:outline-none focus-within:ring-2 focus-within:ring-focus-ring',
        checked ? 'border-primary bg-primary-tint' : 'border-border hover:bg-bg',
      )}
    >
      <input
        type="radio"
        name={name}
        value={value}
        checked={checked}
        onChange={onSelect}
        className="sr-only"
      />
      <span
        className={cn(
          'grid size-9 shrink-0 place-items-center rounded-md',
          checked ? 'bg-primary text-white' : 'bg-primary-tint text-primary',
        )}
      >
        <Icon className="size-4" strokeWidth={1.75} aria-hidden="true" />
      </span>
      <span className="flex min-w-0 flex-col gap-0.5">
        <span className="text-sm font-medium text-text">{label}</span>
        <span className="text-xs leading-relaxed text-text-secondary">{description}</span>
      </span>
      {checked && (
        <CheckCircle2
          className="absolute right-3 top-3 size-4 text-primary"
          strokeWidth={2}
          aria-hidden="true"
        />
      )}
    </label>
  );
}

/** Step 1 - Basic (generated cylinder) vs Manual (hand-edited) configuration. */
function ModeStep({
  mode,
  onPick,
  busy,
  onContinue,
  onCancel,
}: {
  mode: Mode | null;
  onPick: (mode: Mode) => void;
  busy: boolean;
  onContinue: () => void;
  onCancel: () => void;
}) {
  return (
    <DialogContent className="max-w-2xl overscroll-contain">
      <DialogHeader>
        <DialogTitle>Set up TopoSet</DialogTitle>
        <DialogDescription>
          Choose how to write{' '}
          <code className="font-mono text-sm" translate="no">
            {TOPOSET_PATH}
          </code>
          , the dictionary <span className="font-mono text-sm">topoSet</span> reads to
          build named cell sets and zones (e.g. a rotor cell zone).
        </DialogDescription>
      </DialogHeader>

      <fieldset className="min-w-0">
        <legend className="sr-only">Configuration mode</legend>
        <div className="grid gap-2 sm:grid-cols-2">
          <OptionCard
            name="topoSetMode"
            value="basic"
            checked={mode === 'basic'}
            icon={Cylinder}
            label="Basic"
            description="Fill a small form (cell zone name, cylinder axis, radius) and generate the actions."
            onSelect={() => onPick('basic')}
          />
          <OptionCard
            name="topoSetMode"
            value="manual"
            checked={mode === 'manual'}
            icon={SquarePen}
            label="Manual"
            description="Create the file with a starter template and configure the actions yourself."
            onSelect={() => onPick('manual')}
          />
        </div>
      </fieldset>

      <DialogFooter className="mt-2">
        <Button type="button" variant="ghost" onClick={onCancel} disabled={busy}>
          Cancel
        </Button>
        <Button type="button" onClick={onContinue} disabled={!mode} loading={busy}>
          Continue
          <ChevronRight strokeWidth={1.75} aria-hidden="true" />
        </Button>
      </DialogFooter>
    </DialogContent>
  );
}

/** A labeled number input (matches BoundaryConditionDialog's NumberField). */
function NumberField({
  id,
  label,
  unit,
  value,
  onChange,
  helper,
}: {
  id: string;
  label: string;
  unit?: string;
  value: string;
  onChange: (value: string) => void;
  helper?: string;
}) {
  return (
    <div className="flex flex-col gap-1.5">
      <label htmlFor={id} className="text-xs font-medium text-text-secondary">
        {label}
        {unit && <span className="ml-1 font-normal text-text-secondary/80">[{unit}]</span>}
      </label>
      <Input
        id={id}
        type="number"
        inputMode="decimal"
        step="any"
        autoComplete="off"
        value={value}
        onChange={(event) => onChange(event.currentTarget.value)}
        aria-describedby={helper ? `${id}-help` : undefined}
        className="font-mono tabular-nums"
      />
      {helper && (
        <p id={`${id}-help`} className="text-xs text-text-secondary">
          {helper}
        </p>
      )}
    </div>
  );
}

/** A labeled 3-component vector input `(x y z)` (matches BoundaryConditionDialog's VectorField). */
function VectorField({
  label,
  value,
  onChange,
  helper,
}: {
  label: string;
  value: [string, string, string];
  onChange: (value: [string, string, string]) => void;
  helper?: string;
}) {
  const set = (index: number, next: string) => {
    const copy: [string, string, string] = [...value];
    copy[index] = next;
    onChange(copy);
  };
  return (
    <div className="flex flex-col gap-1.5">
      <span className="text-xs font-medium text-text-secondary">{label}</span>
      <div className="grid grid-cols-3 gap-2">
        {(['x', 'y', 'z'] as const).map((component, index) => (
          <Input
            key={component}
            type="number"
            inputMode="decimal"
            step="any"
            autoComplete="off"
            aria-label={`${label} ${component}`}
            value={value[index]}
            onChange={(event) => set(index, event.currentTarget.value)}
            className="font-mono tabular-nums"
          />
        ))}
      </div>
      {helper && <p className="text-xs text-text-secondary">{helper}</p>}
    </div>
  );
}

/** Step 2 (Basic only) - the cylinder cell zone form. */
function CylinderStep({
  cellZone,
  p1,
  p2,
  radius,
  fileExists,
  ready,
  busy,
  onCellZoneChange,
  onP1Change,
  onP2Change,
  onRadiusChange,
  onBack,
  onCreate,
}: {
  cellZone: string;
  p1: [string, string, string];
  p2: [string, string, string];
  radius: string;
  fileExists: boolean;
  ready: boolean;
  busy: boolean;
  onCellZoneChange: (value: string) => void;
  onP1Change: (value: [string, string, string]) => void;
  onP2Change: (value: [string, string, string]) => void;
  onRadiusChange: (value: string) => void;
  onBack: () => void;
  onCreate: () => void;
}) {
  const baseId = useId();

  return (
    <DialogContent className="max-w-2xl max-h-[85vh] overflow-y-auto overscroll-contain">
      <DialogHeader>
        <DialogTitle>Cylindrical cell zone</DialogTitle>
        <DialogDescription>
          Defines a cylinder, selects the cells inside it, then promotes them to a cell zone. This
          writes a <span className="font-mono text-sm">cylinderToCell</span> +{' '}
          <span className="font-mono text-sm">setToCellZone</span> action pair.
        </DialogDescription>
      </DialogHeader>

      {fileExists && (
        <div className="flex items-start gap-2 rounded-md border border-accent/40 bg-accent-tint px-3 py-2.5">
          <Diamond size={10} className="mt-1 text-accent" />
          <p className="text-xs text-text">
            <span className="font-mono" translate="no">
              {TOPOSET_PATH}
            </span>{' '}
            already exists and will be overwritten.
          </p>
        </div>
      )}

      <div className="flex flex-col gap-4">
        <div className="flex flex-col gap-1.5">
          <label htmlFor={`${baseId}-cellzone`} className="text-xs font-medium text-text-secondary">
            Cell zone name
          </label>
          <Input
            id={`${baseId}-cellzone`}
            type="text"
            autoComplete="off"
            spellCheck={false}
            translate="no"
            value={cellZone}
            onChange={(event) => onCellZoneChange(event.currentTarget.value)}
            aria-describedby={`${baseId}-cellzone-help`}
            className="font-mono"
          />
          <p id={`${baseId}-cellzone-help`} className="text-xs text-text-secondary">
            The name written to{' '}
            <code className="font-mono" translate="no">
              constant/polyMesh/cellZones
            </code>{' '}
            once <span className="font-mono">topoSet</span> is run (e.g. the rotor's cell zone).
          </p>
        </div>

        <div className="grid gap-3 sm:grid-cols-2">
          <VectorField
            label="Cylinder start (p1)"
            value={p1}
            onChange={onP1Change}
            helper="One end-cap centre, in metres."
          />
          <VectorField
            label="Cylinder end (p2)"
            value={p2}
            onChange={onP2Change}
            helper="The other end-cap centre, in metres."
          />
        </div>

        <div className="grid gap-3 sm:grid-cols-2">
          <NumberField
            id={`${baseId}-radius`}
            label="Radius"
            unit="m"
            value={radius}
            onChange={onRadiusChange}
          />
        </div>
      </div>

      <DialogFooter className="mt-2">
        <Button type="button" variant="ghost" onClick={onBack} disabled={busy}>
          <ArrowLeft strokeWidth={1.75} aria-hidden="true" />
          Back
        </Button>
        <Button type="button" onClick={onCreate} disabled={!ready} loading={busy}>
          {fileExists ? 'Overwrite file' : 'Create file'}
        </Button>
      </DialogFooter>
    </DialogContent>
  );
}

/** Step 3 - result: what was written, plus the reminder that topoSet still has to run. */
function DoneStep({
  projectId,
  mode,
  onAdjust,
  onClose,
}: {
  projectId: string;
  mode: Mode;
  onAdjust: () => void;
  onClose: () => void;
}) {
  return (
    <DialogContent className="max-w-2xl overscroll-contain">
      <DialogHeader>
        <DialogTitle>
          {mode === 'basic' ? 'Cell zone written' : 'File ready to configure'}
        </DialogTitle>
        <DialogDescription>
          {mode === 'basic'
            ? 'The cylinder cell zone actions were written to the case.'
            : 'The starter template is in the case, ready for you to edit.'}
        </DialogDescription>
      </DialogHeader>

      <div
        role="status"
        className="flex items-start gap-2 rounded-md border border-success/40 bg-success-tint px-4 py-3 text-sm text-text"
      >
        <CheckCircle2 className="mt-0.5 size-4 shrink-0 text-success" strokeWidth={1.75} aria-hidden="true" />
        <span>
          <span className="font-mono" translate="no">
            {TOPOSET_PATH}
          </span>{' '}
          is in the case files.
        </span>
      </div>

      <ul className="flex flex-col gap-1.5">
        <li className="flex items-start gap-2 text-xs text-text-secondary">
          <Diamond size={8} className="mt-[0.3rem] text-primary" />
          <span>
            This only writes the dictionary. Run{' '}
            <span className="font-mono" translate="no">
              topoSet
            </span>{' '}
            yourself on the OpenFOAM server before starting the case, so the cell zone actually
            exists in the mesh.
          </span>
        </li>
      </ul>

      <DialogFooter className="mt-2">
        <Button type="button" variant="ghost" onClick={onAdjust}>
          <ArrowLeft strokeWidth={1.75} aria-hidden="true" />
          Adjust
        </Button>
        <Button asChild variant="secondary">
          <Link to={`/projects/${projectId}/edit`}>
            <SquarePen strokeWidth={1.75} aria-hidden="true" />
            Open files
          </Link>
        </Button>
        <Button type="button" onClick={onClose}>
          Close
        </Button>
      </DialogFooter>
    </DialogContent>
  );
}
