// Pure renderer for the cfMesh dictionary a cartesianMesh run generates
// (system/meshDict), plus the base-size resolver. Kept separate from
// snappyDicts.ts: cfMesh reads ONE surfaceFile (a merged STL or an FMS), sizes
// are ABSOLUTE metres, and its boundary-layer vocabulary differs from snappy.
// A pure function of the CfMeshConfig + the resolved surface path, so it is unit-
// tested with no OpenFOAM toolchain present. cartesianMesh also needs a minimal
// case (system/controlDict, fvSchemes, fvSolution) — those are reused from
// snappyDicts (the `application` value is irrelevant to cartesianMesh).
import type { CfMeshConfig, MeshBounds } from '@dive/shared';

/** Standard OpenFOAM dictionary banner + FoamFile header. */
function foamHeader(object: string): string {
  return `/*--------------------------------*- C++ -*----------------------------------*\\
| =========                 |                                                 |
| \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\\\    /   O peration     | Generated by DIVE Turbinen (cfMesh session)     |
|   \\\\  /    A nd           |                                                 |
|    \\\\/     M anipulation  |                                                 |
\\*---------------------------------------------------------------------------*/
FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    location    "system";
    object      ${object};
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
`;
}

const FOOTER = `
// ************************************************************************* //
`;

/** Round for display without scientific notation. */
function fmt(n: number): string {
  if (!Number.isFinite(n)) return '0';
  return Number(n.toPrecision(6)).toString();
}

/** Euclidean length of the bbox diagonal. */
function diagonal(bounds: MeshBounds): number {
  const dx = bounds.max[0] - bounds.min[0];
  const dy = bounds.max[1] - bounds.min[1];
  const dz = bounds.max[2] - bounds.min[2];
  return Math.sqrt(dx * dx + dy * dy + dz * dz);
}

/**
 * Resolve the base (max) cell size: the configured value when set, else derived
 * from the STL bounds (diagonal / 40, the same coarse base snappy uses). Returns
 * null when neither is available (a raw FMS with no bounds and no configured size)
 * — the caller must reject that, since cartesianMesh needs a maxCellSize.
 */
export function resolveMaxCellSize(config: CfMeshConfig, bounds: MeshBounds | null): number | null {
  if (config.maxCellSize && config.maxCellSize > 0) return config.maxCellSize;
  if (bounds) {
    const diag = diagonal(bounds);
    if (diag > 0) return diag / 40;
  }
  return null;
}

/**
 * Render system/meshDict for cartesianMesh. `surfaceFile` is the path (relative to
 * the case dir) of the merged STL or the FMS; `maxCellSize` is the resolved base
 * size. Optional min/boundary cell sizes and the boundary-layer block are emitted
 * only when set.
 */
export function renderMeshDict(
  config: CfMeshConfig,
  surfaceFile: string,
  maxCellSize: number,
): string {
  const lines: string[] = [`surfaceFile "${surfaceFile}";`, '', `maxCellSize ${fmt(maxCellSize)};`];

  if (config.minCellSize && config.minCellSize > 0) {
    lines.push(`minCellSize ${fmt(config.minCellSize)};`);
  }
  if (config.boundaryCellSize && config.boundaryCellSize > 0) {
    lines.push(`boundaryCellSize ${fmt(config.boundaryCellSize)};`);
  }

  if (config.addLayers.enabled) {
    const layer: string[] = [
      'boundaryLayers',
      '{',
      `    nLayers ${Math.max(1, Math.round(config.addLayers.nLayers))};`,
      `    thicknessRatio ${fmt(Math.max(1, config.addLayers.thicknessRatio))};`,
    ];
    if (config.addLayers.maxFirstLayerThickness && config.addLayers.maxFirstLayerThickness > 0) {
      layer.push(`    maxFirstLayerThickness ${fmt(config.addLayers.maxFirstLayerThickness)};`);
    }
    // Smooth the layer over the whole boundary; standard cfMesh tutorial setting.
    layer.push('    allowDiscontinuity 0;', '    optimiseLayer 1;', '}');
    lines.push('', ...layer);
  }

  return `${foamHeader('meshDict')}
${lines.join('\n')}
${FOOTER}`;
}
