// OpenFOAM case domain helpers: the canonical list of mandatory files, the
// generic-minimal templates used to scaffold the missing base files, and a
// tolerant parser for the mesh boundary patch names.
//
// Scope (v1): purely textual generation. We do NOT presume a specific solver,
// so the generated dictionaries are deliberately minimal, generic, and meant to
// be edited. The only knowledge we inject from the imported mesh is the set of
// boundary patch names, so the generated 0/ fields already reference the right
// patches (the rule that 0/*.boundaryField must cover every polyMesh patch).
//
// See docs/openfoam-fichiers-obligatoires.md for the contract this encodes.

/**
 * The five files that make up the mesh, living under constant/polyMesh/. These
 * are produced by the user's import (e.g. an Ansys/Fluent conversion) and can
 * never be generated by the app — only reported as present or missing.
 */
export const MESH_FILES = [
  'constant/polyMesh/points',
  'constant/polyMesh/faces',
  'constant/polyMesh/owner',
  'constant/polyMesh/neighbour',
  'constant/polyMesh/boundary',
] as const;

/** Path of the boundary file we parse to discover patch names. */
export const BOUNDARY_FILE = 'constant/polyMesh/boundary';

/**
 * The mandatory base files the app can generate on demand: the system/ trio and
 * the minimal 0/ initial fields. constant/<...>Properties are intentionally
 * excluded — they are solver-dependent and we do not presume a solver in v1.
 */
export const BASE_FILE_PATHS = [
  'system/controlDict',
  'system/fvSchemes',
  'system/fvSolution',
  '0/U',
  '0/p',
] as const;

export type BaseFilePath = (typeof BASE_FILE_PATHS)[number];

/** Standard OpenFOAM dictionary banner + FoamFile header. */
function foamHeader(className: string, object: string, location: string): string {
  return `/*--------------------------------*- C++ -*----------------------------------*\\
| =========                 |                                                 |
| \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\\\    /   O peration     | Generated by DIVE Turbinen (generic minimal)    |
|   \\\\  /    A nd           |                                                 |
|    \\\\/     M anipulation  |                                                 |
\\*---------------------------------------------------------------------------*/
FoamFile
{
    version     2.0;
    format      ascii;
    class       ${className};
    location    "${location}";
    object      ${object};
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
`;
}

const FOAM_FOOTER = `
// ************************************************************************* //
`;

/** Build a boundaryField block, one entry per discovered patch (zeroGradient).
 * Falls back to an editable placeholder when no patches are known. */
function boundaryFieldBlock(patches: string[]): string {
  if (patches.length === 0) {
    return `boundaryField
{
    // No mesh patches detected yet. Import the mesh (constant/polyMesh/) and
    // regenerate, or add one entry per patch from constant/polyMesh/boundary.
}`;
  }
  const entries = patches
    .map(
      (patch) => `    ${patch}
    {
        type            zeroGradient;
    }`,
    )
    .join('\n');
  return `boundaryField
{
${entries}
}`;
}

/** system/controlDict — generic transient/steady skeleton (edit `application`). */
function controlDict(): string {
  return `${foamHeader('dictionary', 'controlDict', 'system')}
// Set this to the solver you run (e.g. simpleFoam, pimpleFoam, foamRun).
application     foamRun;

startFrom       startTime;
startTime       0;

stopAt          endTime;
endTime         1;

deltaT          1;

writeControl    timeStep;
writeInterval   1;

purgeWrite      0;

writeFormat     ascii;
writePrecision  6;
writeCompression off;

timeFormat      general;
timePrecision   6;

runTimeModifiable true;
${FOAM_FOOTER}`;
}

/** system/fvSchemes — generic discretisation defaults. */
function fvSchemes(): string {
  return `${foamHeader('dictionary', 'fvSchemes', 'system')}
ddtSchemes
{
    default         steadyState;
}

gradSchemes
{
    default         Gauss linear;
}

divSchemes
{
    default         none;
}

laplacianSchemes
{
    default         Gauss linear corrected;
}

interpolationSchemes
{
    default         linear;
}

snGradSchemes
{
    default         corrected;
}
${FOAM_FOOTER}`;
}

/** system/fvSolution — generic linear solvers + SIMPLE skeleton. */
function fvSolution(): string {
  return `${foamHeader('dictionary', 'fvSolution', 'system')}
solvers
{
    "(p|U|k|epsilon|omega|nut)"
    {
        solver          PBiCGStab;
        preconditioner  DILU;
        tolerance       1e-06;
        relTol          0.1;
    }
}

SIMPLE
{
    nNonOrthogonalCorrectors 0;
}

relaxationFactors
{
    // Add field/equation relaxation factors for your solver here.
}
${FOAM_FOOTER}`;
}

/** 0/U — velocity field; boundaryField covers every discovered patch. */
function fieldU(patches: string[]): string {
  return `${foamHeader('volVectorField', 'U', '0')}
dimensions      [0 1 -1 0 0 0 0];

internalField   uniform (0 0 0);

${boundaryFieldBlock(patches)}
${FOAM_FOOTER}`;
}

/** 0/p — pressure field; boundaryField covers every discovered patch. */
function fieldP(patches: string[]): string {
  return `${foamHeader('volScalarField', 'p', '0')}
dimensions      [0 2 -2 0 0 0 0];

internalField   uniform 0;

${boundaryFieldBlock(patches)}
${FOAM_FOOTER}`;
}

/**
 * Render the content of a single base file. `patches` is used only by the 0/
 * fields so their boundaryField references the imported mesh's patches.
 */
export function renderBaseFile(path: BaseFilePath, patches: string[]): string {
  switch (path) {
    case 'system/controlDict':
      return controlDict();
    case 'system/fvSchemes':
      return fvSchemes();
    case 'system/fvSolution':
      return fvSolution();
    case '0/U':
      return fieldU(patches);
    case '0/p':
      return fieldP(patches);
  }
}

/**
 * Parse the names of the boundary patches from a constant/polyMesh/boundary
 * file. Tolerant by design: strips comments, then collects every `name { ... }`
 * block in the file (excluding the FoamFile header). De-duplicated, order
 * preserved. Returns [] for unparhseable or empty input.
 */
export function parseBoundaryPatches(content: string): string[] {
  const withoutBlockComments = content.replace(/\/\*[\s\S]*?\*\//g, '');
  const cleaned = withoutBlockComments.replace(/\/\/.*$/gm, '');

  const names: string[] = [];
  const blockStart = /([A-Za-z_][A-Za-z0-9_-]*)\s*\{/g;
  let match: RegExpExecArray | null;
  while ((match = blockStart.exec(cleaned)) !== null) {
    const name = match[1];
    if (name === 'FoamFile') continue;
    names.push(name);
  }
  return [...new Set(names)];
}
