// OpenFOAM case domain helpers: the canonical list of mandatory files, the
// generic-minimal templates used to scaffold the missing base files, and a
// tolerant parser for the mesh boundary patch names.
//
// Scope (v1): purely textual generation. We do NOT presume a specific solver,
// so the generated dictionaries are deliberately minimal, generic, and meant to
// be edited. The only knowledge we inject from the imported mesh is the set of
// boundary patch names, so the generated 0/ fields already reference the right
// patches (the rule that 0/*.boundaryField must cover every polyMesh patch).
//
// See docs/openfoam-fichiers-obligatoires.md for the contract this encodes.

/**
 * The five files that make up the mesh, living under constant/polyMesh/. These
 * are produced by the user's import (e.g. an Ansys/Fluent conversion) and can
 * never be generated by the app — only reported as present or missing.
 */
export const MESH_FILES = [
  'constant/polyMesh/points',
  'constant/polyMesh/faces',
  'constant/polyMesh/owner',
  'constant/polyMesh/neighbour',
  'constant/polyMesh/boundary',
] as const;

/** Path of the boundary file we parse to discover patch names. */
export const BOUNDARY_FILE = 'constant/polyMesh/boundary';

/**
 * The mandatory base files the app can generate on demand: the system/ trio and
 * the minimal 0/ initial fields. constant/<...>Properties are intentionally
 * excluded — they are solver-dependent and we do not presume a solver in v1.
 */
export const BASE_FILE_PATHS = [
  'system/controlDict',
  'system/fvSchemes',
  'system/fvSolution',
  '0/U',
  '0/p',
] as const;

export type BaseFilePath = (typeof BASE_FILE_PATHS)[number];

/** Standard OpenFOAM dictionary banner + FoamFile header. */
function foamHeader(className: string, object: string, location: string): string {
  return `/*--------------------------------*- C++ -*----------------------------------*\\
| =========                 |                                                 |
| \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\\\    /   O peration     | Generated by DIVE Turbinen (generic minimal)    |
|   \\\\  /    A nd           |                                                 |
|    \\\\/     M anipulation  |                                                 |
\\*---------------------------------------------------------------------------*/
FoamFile
{
    version     2.0;
    format      ascii;
    class       ${className};
    location    "${location}";
    object      ${object};
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
`;
}

const FOAM_FOOTER = `
// ************************************************************************* //
`;

/** Build a boundaryField block, one entry per discovered patch (zeroGradient).
 * Falls back to an editable placeholder when no patches are known. */
function boundaryFieldBlock(patches: string[]): string {
  if (patches.length === 0) {
    return `boundaryField
{
    // No mesh patches detected yet. Import the mesh (constant/polyMesh/) and
    // regenerate, or add one entry per patch from constant/polyMesh/boundary.
}`;
  }
  const entries = patches
    .map(
      (patch) => `    ${patch}
    {
        type            zeroGradient;
    }`,
    )
    .join('\n');
  return `boundaryField
{
${entries}
}`;
}

/** system/controlDict — generic transient/steady skeleton (edit `application`). */
function controlDict(): string {
  return `${foamHeader('dictionary', 'controlDict', 'system')}
// Set this to the solver you run (e.g. simpleFoam, pimpleFoam, foamRun).
application     foamRun;

startFrom       startTime;
startTime       0;

stopAt          endTime;
endTime         1;

deltaT          1;

writeControl    timeStep;
writeInterval   1;

purgeWrite      0;

writeFormat     ascii;
writePrecision  6;
writeCompression off;

timeFormat      general;
timePrecision   6;

runTimeModifiable true;
${FOAM_FOOTER}`;
}

/** system/fvSchemes — generic discretisation defaults. */
function fvSchemes(): string {
  return `${foamHeader('dictionary', 'fvSchemes', 'system')}
ddtSchemes
{
    default         steadyState;
}

gradSchemes
{
    default         Gauss linear;
}

divSchemes
{
    default         none;
}

laplacianSchemes
{
    default         Gauss linear corrected;
}

interpolationSchemes
{
    default         linear;
}

snGradSchemes
{
    default         corrected;
}
${FOAM_FOOTER}`;
}

/** system/fvSolution — generic linear solvers + SIMPLE skeleton. */
function fvSolution(): string {
  return `${foamHeader('dictionary', 'fvSolution', 'system')}
solvers
{
    "(p|U|k|epsilon|omega|nut)"
    {
        solver          PBiCGStab;
        preconditioner  DILU;
        tolerance       1e-06;
        relTol          0.1;
    }
}

SIMPLE
{
    nNonOrthogonalCorrectors 0;
}

relaxationFactors
{
    // Add field/equation relaxation factors for your solver here.
}
${FOAM_FOOTER}`;
}

/** 0/U — velocity field; boundaryField covers every discovered patch. */
function fieldU(patches: string[]): string {
  return `${foamHeader('volVectorField', 'U', '0')}
dimensions      [0 1 -1 0 0 0 0];

internalField   uniform (0 0 0);

${boundaryFieldBlock(patches)}
${FOAM_FOOTER}`;
}

/** 0/p — pressure field; boundaryField covers every discovered patch. */
function fieldP(patches: string[]): string {
  return `${foamHeader('volScalarField', 'p', '0')}
dimensions      [0 2 -2 0 0 0 0];

internalField   uniform 0;

${boundaryFieldBlock(patches)}
${FOAM_FOOTER}`;
}

/**
 * Render the content of a single base file. `patches` is used only by the 0/
 * fields so their boundaryField references the imported mesh's patches.
 */
export function renderBaseFile(path: BaseFilePath, patches: string[]): string {
  switch (path) {
    case 'system/controlDict':
      return controlDict();
    case 'system/fvSchemes':
      return fvSchemes();
    case 'system/fvSolution':
      return fvSolution();
    case '0/U':
      return fieldU(patches);
    case '0/p':
      return fieldP(patches);
  }
}

/** A valid OpenFOAM patch name: a "word" token (letter/underscore start). */
const PATCH_NAME_RE = /^[A-Za-z_][A-Za-z0-9_]*$/;

/** Is `name` a syntactically valid OpenFOAM patch name? */
export function isValidPatchName(name: string): boolean {
  return PATCH_NAME_RE.test(name);
}

/** Escape a string for safe use inside a RegExp. */
function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Replace a patch block header `from { … }` with `to { … }`. A patch name is the
 * only token immediately followed (across optional whitespace/newlines) by `{`,
 * so this targets the dictionary header and never a value like `type from;` or a
 * group reference `1(from)`. The preceding delimiter (start / whitespace / `(`)
 * is preserved.
 */
function renamePatchHeader(content: string, from: string, to: string): string {
  const re = new RegExp(`(^|[\\s(])${escapeRegExp(from)}(\\s*\\{)`, 'g');
  return content.replace(re, `$1${to}$2`);
}

/**
 * Rename a patch in a constant/polyMesh/boundary file. The only `name { … }`
 * blocks there are the patch entries (the FoamFile header is named `FoamFile`),
 * so a whole-file header rename is safe.
 */
export function renameBoundaryPatch(content: string, from: string, to: string): string {
  return renamePatchHeader(content, from, to);
}

/**
 * Find the brace span of the `boundaryField { … }` dictionary in a field file,
 * or null when absent. Brace-matched from the first `{` after the keyword.
 */
function boundaryFieldSpan(content: string): { open: number; close: number } | null {
  const keyword = content.search(/\bboundaryField\b/);
  if (keyword < 0) return null;
  const open = content.indexOf('{', keyword);
  if (open < 0) return null;
  let depth = 0;
  for (let i = open; i < content.length; i += 1) {
    const char = content[i];
    if (char === '{') depth += 1;
    else if (char === '}') {
      depth -= 1;
      if (depth === 0) return { open, close: i };
    }
  }
  return null;
}

/**
 * Rename a patch entry inside a field file's `boundaryField` block only (so a
 * patch name that happens to appear elsewhere — a coded `functions` block, a
 * comment — is left untouched). Returns the content unchanged when the file has
 * no boundaryField.
 */
export function renameFieldBoundaryPatch(content: string, from: string, to: string): string {
  const span = boundaryFieldSpan(content);
  if (!span) return content;
  const before = content.slice(0, span.open);
  const block = content.slice(span.open, span.close + 1);
  const after = content.slice(span.close + 1);
  return before + renamePatchHeader(block, from, to) + after;
}

/**
 * Parse the names of the boundary patches from a constant/polyMesh/boundary
 * file. Tolerant by design: strips comments, then collects every `name { ... }`
 * block in the file (excluding the FoamFile header). De-duplicated, order
 * preserved. Returns [] for unparhseable or empty input.
 */
export function parseBoundaryPatches(content: string): string[] {
  const withoutBlockComments = content.replace(/\/\*[\s\S]*?\*\//g, '');
  const cleaned = withoutBlockComments.replace(/\/\/.*$/gm, '');

  const names: string[] = [];
  const blockStart = /([A-Za-z_][A-Za-z0-9_-]*)\s*\{/g;
  let match: RegExpExecArray | null;
  while ((match = blockStart.exec(cleaned)) !== null) {
    const name = match[1];
    if (name === 'FoamFile') continue;
    names.push(name);
  }
  return [...new Set(names)];
}
