// OpenFOAM case domain helpers: the canonical list of mandatory files, the
// generic-minimal templates used to scaffold the missing base files, and a
// tolerant parser for the mesh boundary patch names.
//
// Scope (v1): purely textual generation. We do NOT presume a specific solver,
// so the generated dictionaries are deliberately minimal, generic, and meant to
// be edited. The only knowledge we inject from the imported mesh is the set of
// boundary patch names, so the generated 0/ fields already reference the right
// patches (the rule that 0/*.boundaryField must cover every polyMesh patch).
//
// See docs/openfoam-fichiers-obligatoires.md for the contract this encodes.

/**
 * The five files that make up the mesh, living under constant/polyMesh/. These
 * are produced by the user's import (e.g. an Ansys/Fluent conversion) and can
 * never be generated by the app — only reported as present or missing.
 */
export const MESH_FILES = [
  'constant/polyMesh/points',
  'constant/polyMesh/faces',
  'constant/polyMesh/owner',
  'constant/polyMesh/neighbour',
  'constant/polyMesh/boundary',
] as const;

/** Path of the boundary file we parse to discover patch names. */
export const BOUNDARY_FILE = 'constant/polyMesh/boundary';

/**
 * The mandatory base files the app can generate on demand: the system/ trio and
 * the minimal 0/ initial fields. constant/<...>Properties are intentionally
 * excluded — they are solver-dependent and we do not presume a solver in v1.
 */
export const BASE_FILE_PATHS = [
  'system/controlDict',
  'system/fvSchemes',
  'system/fvSolution',
  '0/U',
  '0/p',
] as const;

export type BaseFilePath = (typeof BASE_FILE_PATHS)[number];

/** Standard OpenFOAM dictionary banner + FoamFile header. */
function foamHeader(className: string, object: string, location: string): string {
  return `/*--------------------------------*- C++ -*----------------------------------*\\
| =========                 |                                                 |
| \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\\\    /   O peration     | Generated by DIVE Turbinen (generic minimal)    |
|   \\\\  /    A nd           |                                                 |
|    \\\\/     M anipulation  |                                                 |
\\*---------------------------------------------------------------------------*/
FoamFile
{
    version     2.0;
    format      ascii;
    class       ${className};
    location    "${location}";
    object      ${object};
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
`;
}

const FOAM_FOOTER = `
// ************************************************************************* //
`;

/** Build a boundaryField block, one entry per discovered patch (zeroGradient).
 * Falls back to an editable placeholder when no patches are known. */
function boundaryFieldBlock(patches: string[]): string {
  if (patches.length === 0) {
    return `boundaryField
{
    // No mesh patches detected yet. Import the mesh (constant/polyMesh/) and
    // regenerate, or add one entry per patch from constant/polyMesh/boundary.
}`;
  }
  const entries = patches
    .map(
      (patch) => `    ${patch}
    {
        type            zeroGradient;
    }`,
    )
    .join('\n');
  return `boundaryField
{
${entries}
}`;
}

/** system/controlDict — generic transient/steady skeleton (edit `application`). */
function controlDict(): string {
  return `${foamHeader('dictionary', 'controlDict', 'system')}
// Set this to the solver you run (e.g. simpleFoam, pimpleFoam, foamRun).
application     foamRun;

startFrom       startTime;
startTime       0;

stopAt          endTime;
endTime         1;

deltaT          1;

writeControl    timeStep;
writeInterval   1;

purgeWrite      0;

writeFormat     ascii;
writePrecision  6;
writeCompression off;

timeFormat      general;
timePrecision   6;

runTimeModifiable true;
${FOAM_FOOTER}`;
}

/** system/fvSchemes — generic discretisation defaults. */
function fvSchemes(): string {
  return `${foamHeader('dictionary', 'fvSchemes', 'system')}
ddtSchemes
{
    default         steadyState;
}

gradSchemes
{
    default         Gauss linear;
}

divSchemes
{
    default         none;
}

laplacianSchemes
{
    default         Gauss linear corrected;
}

interpolationSchemes
{
    default         linear;
}

snGradSchemes
{
    default         corrected;
}
${FOAM_FOOTER}`;
}

/** system/fvSolution — generic linear solvers + SIMPLE skeleton. */
function fvSolution(): string {
  return `${foamHeader('dictionary', 'fvSolution', 'system')}
solvers
{
    "(p|U|k|epsilon|omega|nut)"
    {
        solver          PBiCGStab;
        preconditioner  DILU;
        tolerance       1e-06;
        relTol          0.1;
    }
}

SIMPLE
{
    nNonOrthogonalCorrectors 0;
}

relaxationFactors
{
    // Add field/equation relaxation factors for your solver here.
}
${FOAM_FOOTER}`;
}

/** 0/U — velocity field; boundaryField covers every discovered patch. */
function fieldU(patches: string[]): string {
  return `${foamHeader('volVectorField', 'U', '0')}
dimensions      [0 1 -1 0 0 0 0];

internalField   uniform (0 0 0);

${boundaryFieldBlock(patches)}
${FOAM_FOOTER}`;
}

/** 0/p — pressure field; boundaryField covers every discovered patch. */
function fieldP(patches: string[]): string {
  return `${foamHeader('volScalarField', 'p', '0')}
dimensions      [0 2 -2 0 0 0 0];

internalField   uniform 0;

${boundaryFieldBlock(patches)}
${FOAM_FOOTER}`;
}

/**
 * Render the content of a single base file. `patches` is used only by the 0/
 * fields so their boundaryField references the imported mesh's patches.
 */
export function renderBaseFile(path: BaseFilePath, patches: string[]): string {
  switch (path) {
    case 'system/controlDict':
      return controlDict();
    case 'system/fvSchemes':
      return fvSchemes();
    case 'system/fvSolution':
      return fvSolution();
    case '0/U':
      return fieldU(patches);
    case '0/p':
      return fieldP(patches);
  }
}

// ---------------------------------------------------------------------------
// Runnable simpleFoam case (Solver tab).
//
// scaffoldCase above produces a *generic*, solver-agnostic skeleton (foamRun,
// `div none`, empty SIMPLE) that does NOT actually run a solver. To make a case
// runnable by simpleFoam (steady incompressible RANS, the MVP solver), we need a
// few more files and solver-correct numerics. These renderers generate a case
// that *executes* simpleFoam; the boundary conditions are generic (zeroGradient)
// and meant to be refined in the in-app editor — same philosophy as the base
// scaffold, just tuned for one concrete solver.
// ---------------------------------------------------------------------------

/**
 * The files a case needs to be runnable by simpleFoam, beyond the mesh. The
 * system trio and 0/{U,p} overlap with BASE_FILE_PATHS but are rendered here in
 * solver-correct form (filled divSchemes, residualControl, application
 * simpleFoam). constant/{transport,turbulence}Properties and 0/{k,omega,nut} are
 * the turbulence/transport setup the generic scaffold deliberately omits.
 */
export const SOLVER_FILE_PATHS = [
  'system/controlDict',
  'system/fvSchemes',
  'system/fvSolution',
  'constant/transportProperties',
  'constant/turbulenceProperties',
  '0/U',
  '0/p',
  '0/k',
  '0/omega',
  '0/nut',
] as const;

export type SolverFilePath = (typeof SOLVER_FILE_PATHS)[number];

/** system/controlDict tuned for a steady simpleFoam run. */
function simpleFoamControlDict(): string {
  return `${foamHeader('dictionary', 'controlDict', 'system')}
application     simpleFoam;

startFrom       startTime;
startTime       0;

stopAt          endTime;
endTime         1000;

deltaT          1;

writeControl    timeStep;
writeInterval   100;

purgeWrite      0;

writeFormat     ascii;
writePrecision  6;
writeCompression off;

timeFormat      general;
timePrecision   6;

runTimeModifiable true;
${FOAM_FOOTER}`;
}

/** system/fvSchemes with concrete divergence schemes for simpleFoam + k-omega SST. */
function simpleFoamFvSchemes(): string {
  return `${foamHeader('dictionary', 'fvSchemes', 'system')}
ddtSchemes
{
    default         steadyState;
}

gradSchemes
{
    default         Gauss linear;
}

divSchemes
{
    default         none;
    div(phi,U)      bounded Gauss linearUpwind grad(U);
    div(phi,k)      bounded Gauss upwind;
    div(phi,omega)  bounded Gauss upwind;
    div((nuEff*dev2(T(grad(U))))) Gauss linear;
}

laplacianSchemes
{
    default         Gauss linear corrected;
}

interpolationSchemes
{
    default         linear;
}

snGradSchemes
{
    default         corrected;
}

wallDist
{
    method          meshWave;
}
${FOAM_FOOTER}`;
}

/** system/fvSolution with a real solver setup, residualControl and relaxation. */
function simpleFoamFvSolution(): string {
  return `${foamHeader('dictionary', 'fvSolution', 'system')}
solvers
{
    p
    {
        solver          GAMG;
        smoother        GaussSeidel;
        tolerance       1e-06;
        relTol          0.1;
    }

    "(U|k|omega)"
    {
        solver          smoothSolver;
        smoother        symGaussSeidel;
        tolerance       1e-05;
        relTol          0.1;
    }
}

SIMPLE
{
    nNonOrthogonalCorrectors 0;
    consistent      yes;

    // No fixedValue pressure patch in the generic setup, so pin a reference.
    pRefCell        0;
    pRefValue       0;

    residualControl
    {
        p               1e-4;
        U               1e-4;
        "(k|omega)"     1e-4;
    }
}

relaxationFactors
{
    fields
    {
        p               0.3;
    }
    equations
    {
        U               0.7;
        "(k|omega)"     0.7;
    }
}
${FOAM_FOOTER}`;
}

/** constant/transportProperties — Newtonian, kinematic viscosity nu. */
function transportProperties(): string {
  return `${foamHeader('dictionary', 'transportProperties', 'constant')}
transportModel  Newtonian;

// Kinematic viscosity nu [m^2/s]. Default ~ air at room temperature; edit me.
nu              [0 2 -1 0 0 0 0] 1e-05;
${FOAM_FOOTER}`;
}

/** constant/turbulenceProperties — RAS with the k-omega SST model. */
function turbulenceProperties(): string {
  return `${foamHeader('dictionary', 'turbulenceProperties', 'constant')}
simulationType  RAS;

RAS
{
    RASModel        kOmegaSST;
    turbulence      on;
    printCoeffs     on;
}
${FOAM_FOOTER}`;
}

/** 0/k — turbulent kinetic energy; boundaryField covers every discovered patch. */
function fieldK(patches: string[]): string {
  return `${foamHeader('volScalarField', 'k', '0')}
dimensions      [0 2 -2 0 0 0 0];

internalField   uniform 0.1;

${boundaryFieldBlock(patches)}
${FOAM_FOOTER}`;
}

/** 0/omega — specific dissipation rate; boundaryField covers every patch. */
function fieldOmega(patches: string[]): string {
  return `${foamHeader('volScalarField', 'omega', '0')}
dimensions      [0 0 -1 0 0 0 0];

internalField   uniform 1;

${boundaryFieldBlock(patches)}
${FOAM_FOOTER}`;
}

/** 0/nut — turbulent viscosity (computed by the model); boundaryField per patch. */
function fieldNut(patches: string[]): string {
  return `${foamHeader('volScalarField', 'nut', '0')}
dimensions      [0 2 -1 0 0 0 0];

internalField   uniform 0;

${boundaryFieldBlock(patches)}
${FOAM_FOOTER}`;
}

/**
 * Render the content of a single simpleFoam solver file. `patches` is used only
 * by the 0/ fields so their boundaryField references the imported mesh's patches.
 */
export function renderSolverFile(path: SolverFilePath, patches: string[]): string {
  switch (path) {
    case 'system/controlDict':
      return simpleFoamControlDict();
    case 'system/fvSchemes':
      return simpleFoamFvSchemes();
    case 'system/fvSolution':
      return simpleFoamFvSolution();
    case 'constant/transportProperties':
      return transportProperties();
    case 'constant/turbulenceProperties':
      return turbulenceProperties();
    case '0/U':
      return fieldU(patches);
    case '0/p':
      return fieldP(patches);
    case '0/k':
      return fieldK(patches);
    case '0/omega':
      return fieldOmega(patches);
    case '0/nut':
      return fieldNut(patches);
  }
}

/**
 * Read the solver name from a controlDict's `application` keyword, or null when
 * absent/unparseable. Tolerant: ignores comments before the keyword.
 */
export function parseApplication(controlDictContent: string): string | null {
  const cleaned = controlDictContent
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/\/\/.*$/gm, '');
  const match = cleaned.match(/\bapplication\s+([A-Za-z_][A-Za-z0-9_]*)\s*;/);
  return match ? match[1] : null;
}

/**
 * Set the `application` keyword in a controlDict to `solver`. Replaces an
 * existing `application <x>;` line (preserving indentation); if none is present,
 * inserts one just after the FoamFile header banner. Used by "Make runnable for
 * simpleFoam" so a case scaffolded generically (`application foamRun`) actually
 * targets the solver its turbulence/transport files are written for.
 */
export function setApplication(content: string, solver: string): string {
  if (/^[ \t]*application[ \t]+[A-Za-z_][A-Za-z0-9_]*[ \t]*;/m.test(content)) {
    return content.replace(
      /^([ \t]*)application[ \t]+[A-Za-z_][A-Za-z0-9_]*[ \t]*;/m,
      `$1application     ${solver};`,
    );
  }
  const line = `application     ${solver};`;
  const banner = content.indexOf('// * * *');
  if (banner >= 0) {
    const newline = content.indexOf('\n', banner);
    if (newline >= 0) {
      return `${content.slice(0, newline + 1)}\n${line}\n${content.slice(newline + 1)}`;
    }
  }
  return `${line}\n${content}`;
}

/** A valid OpenFOAM patch name: a "word" token (letter/underscore start). */
const PATCH_NAME_RE = /^[A-Za-z_][A-Za-z0-9_]*$/;

/** Is `name` a syntactically valid OpenFOAM patch name? */
export function isValidPatchName(name: string): boolean {
  return PATCH_NAME_RE.test(name);
}

/** Escape a string for safe use inside a RegExp. */
function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Replace a patch block header `from { … }` with `to { … }`. A patch name is the
 * only token immediately followed (across optional whitespace/newlines) by `{`,
 * so this targets the dictionary header and never a value like `type from;` or a
 * group reference `1(from)`. The preceding delimiter (start / whitespace / `(`)
 * is preserved.
 */
function renamePatchHeader(content: string, from: string, to: string): string {
  const re = new RegExp(`(^|[\\s(])${escapeRegExp(from)}(\\s*\\{)`, 'g');
  return content.replace(re, `$1${to}$2`);
}

/**
 * Rename a patch in a constant/polyMesh/boundary file. The only `name { … }`
 * blocks there are the patch entries (the FoamFile header is named `FoamFile`),
 * so a whole-file header rename is safe.
 */
export function renameBoundaryPatch(content: string, from: string, to: string): string {
  return renamePatchHeader(content, from, to);
}

/**
 * Find the brace span of the `boundaryField { … }` dictionary in a field file,
 * or null when absent. Brace-matched from the first `{` after the keyword.
 */
function boundaryFieldSpan(content: string): { open: number; close: number } | null {
  const keyword = content.search(/\bboundaryField\b/);
  if (keyword < 0) return null;
  const open = content.indexOf('{', keyword);
  if (open < 0) return null;
  let depth = 0;
  for (let i = open; i < content.length; i += 1) {
    const char = content[i];
    if (char === '{') depth += 1;
    else if (char === '}') {
      depth -= 1;
      if (depth === 0) return { open, close: i };
    }
  }
  return null;
}

/**
 * Rename a patch entry inside a field file's `boundaryField` block only (so a
 * patch name that happens to appear elsewhere — a coded `functions` block, a
 * comment — is left untouched). Returns the content unchanged when the file has
 * no boundaryField.
 */
export function renameFieldBoundaryPatch(content: string, from: string, to: string): string {
  const span = boundaryFieldSpan(content);
  if (!span) return content;
  const before = content.slice(0, span.open);
  const block = content.slice(span.open, span.close + 1);
  const after = content.slice(span.close + 1);
  return before + renamePatchHeader(block, from, to) + after;
}

/** Index of the `}` matching the `{` at `open`, or -1 when unbalanced. */
function matchBrace(content: string, open: number): number {
  let depth = 0;
  for (let i = open; i < content.length; i += 1) {
    const char = content[i];
    if (char === '{') depth += 1;
    else if (char === '}') {
      depth -= 1;
      if (depth === 0) return i;
    }
  }
  return -1;
}

/**
 * Set the `type` of a patch block in a constant/polyMesh/boundary file. Targets
 * the patch's own dictionary header (`name { … }`), replacing its `type X;` (or
 * inserting one if absent). Returns the content unchanged when the patch is
 * absent. A patch name appearing as a value (`type name;`) is never matched
 * because the header requires the name to be immediately followed by `{`.
 */
export function setBoundaryPatchType(content: string, patch: string, type: string): string {
  const header = new RegExp(`(?:^|[\\s(])${escapeRegExp(patch)}\\s*\\{`, 'm');
  const match = header.exec(content);
  if (!match) return content;
  const open = content.indexOf('{', match.index);
  const close = matchBrace(content, open);
  if (close < 0) return content;

  const block = content.slice(open, close + 1);
  const retyped = block.replace(/(\btype\s+)[A-Za-z_][A-Za-z0-9_]*(\s*;)/, `$1${type}$2`);
  const next = retyped !== block ? retyped : block.replace('{', `{\n        type            ${type};`);
  return content.slice(0, open) + next + content.slice(close + 1);
}

/** Read the BC `type` of a patch entry inside a field's boundaryField, or null. */
export function getFieldPatchType(content: string, patch: string): string | null {
  const span = boundaryFieldSpan(content);
  if (!span) return null;
  const block = content.slice(span.open, span.close + 1);
  const header = new RegExp(`(?:^|[\\s])${escapeRegExp(patch)}\\s*\\{`, 'm');
  const match = header.exec(block);
  if (!match) return null;
  const open = block.indexOf('{', match.index);
  const close = matchBrace(block, open);
  if (close < 0) return null;
  const entry = block.slice(open, close + 1);
  const typeMatch = entry.match(/\btype\s+([A-Za-z_][A-Za-z0-9_]*)\s*;/);
  return typeMatch ? typeMatch[1] : null;
}

/**
 * Replace a patch entry inside a field's boundaryField with a minimal
 * `{ type <bcType>; }`. Used to propagate a constraint patch type (empty /
 * symmetry / …) into the 0/ fields, where the field BC must match the geometric
 * type exactly (those BCs take no other keywords). Returns content unchanged when
 * the field has no boundaryField or no such patch entry.
 */
export function setFieldPatchType(content: string, patch: string, bcType: string): string {
  const span = boundaryFieldSpan(content);
  if (!span) return content;
  const block = content.slice(span.open, span.close + 1);
  const header = new RegExp(`(?:^|[\\s])${escapeRegExp(patch)}\\s*\\{`, 'm');
  const match = header.exec(block);
  if (!match) return content;
  const open = block.indexOf('{', match.index);
  const close = matchBrace(block, open);
  if (close < 0) return content;
  const entry = `{\n        type            ${bcType};\n    }`;
  const newBlock = block.slice(0, open) + entry + block.slice(close + 1);
  return content.slice(0, span.open) + newBlock + content.slice(span.close + 1);
}

/**
 * Parse the names of the boundary patches from a constant/polyMesh/boundary
 * file. Tolerant by design: strips comments, then collects every `name { ... }`
 * block in the file (excluding the FoamFile header). De-duplicated, order
 * preserved. Returns [] for unparhseable or empty input.
 */
export function parseBoundaryPatches(content: string): string[] {
  const withoutBlockComments = content.replace(/\/\*[\s\S]*?\*\//g, '');
  const cleaned = withoutBlockComments.replace(/\/\/.*$/gm, '');

  const names: string[] = [];
  const blockStart = /([A-Za-z_][A-Za-z0-9_-]*)\s*\{/g;
  let match: RegExpExecArray | null;
  while ((match = blockStart.exec(cleaned)) !== null) {
    const name = match[1];
    if (name === 'FoamFile') continue;
    names.push(name);
  }
  return [...new Set(names)];
}
