// Pure string renderers for the OpenFOAM dictionaries a meshing run generates.
//
// Kept separate from openfoamCase.ts (whose base files are solver-oriented):
// snappyHexMesh needs mesh-only variants — controlDict with `application
// snappyHexMesh`, a background blockMeshDict sized from the STL bounds, a
// surfaceFeatureExtractDict, and the snappyHexMeshDict itself. Everything is a
// pure function of the STL bounds + the user's SnappyConfig, so the whole set is
// computed (and unit-tested) with no OpenFOAM toolchain present.
import type { AddLayersConfig, DomainType, MeshBounds, SnappyConfig } from '@dive/shared';

/**
 * A sensible `minThickness` for the layer controls: a quarter of the final layer
 * thickness. In relative mode that is a small fraction of the cell; in absolute
 * mode a small length — either way below the layer that must be grown.
 */
function minLayerThickness(layers: AddLayersConfig): number {
  return Math.max(layers.finalLayerThickness * 0.25, 1e-6);
}

/** Standard OpenFOAM dictionary banner + FoamFile header. */
function foamHeader(className: string, object: string, location: string): string {
  return `/*--------------------------------*- C++ -*----------------------------------*\\
| =========                 |                                                 |
| \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\\\    /   O peration     | Generated by DIVE Turbinen (meshing session)    |
|   \\\\  /    A nd           |                                                 |
|    \\\\/     M anipulation  |                                                 |
\\*---------------------------------------------------------------------------*/
FoamFile
{
    version     2.0;
    format      ascii;
    class       ${className};
    location    "${location}";
    object      ${object};
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
`;
}

const FOOTER = `
// ************************************************************************* //
`;

/** A region name for an STL: its basename stem reduced to a valid OpenFOAM word. */
export function regionNameFor(stlFileName: string): string {
  const stem = stlFileName.replace(/\.[^.]+$/, '');
  const word = stem.replace(/[^A-Za-z0-9_]+/g, '_').replace(/^_+|_+$/g, '');
  return word || 'surface';
}

/** The resolved background-box geometry + keep-point for a run. */
export interface SnappyDomain {
  boxMin: [number, number, number];
  boxMax: [number, number, number];
  counts: [number, number, number];
  cellSize: number;
  locationInMesh: [number, number, number];
}

/** Euclidean length of the bbox diagonal. */
function diagonal(bounds: MeshBounds): number {
  const dx = bounds.max[0] - bounds.min[0];
  const dy = bounds.max[1] - bounds.min[1];
  const dz = bounds.max[2] - bounds.min[2];
  return Math.sqrt(dx * dx + dy * dy + dz * dz);
}

/** Clamp a cell count into a sane range (never 0; guard against a runaway tiny cell). */
function clampCount(n: number): number {
  if (!Number.isFinite(n) || n < 1) return 1;
  return Math.min(500, Math.round(n));
}

/**
 * Resolve the background box, cell counts, and keep-point from the STL bounds and
 * the config. `baseCellSize`/`locationInMesh` null means "derive here":
 *  - cell size defaults to bbox-diagonal / 40 (a reasonable coarse base);
 *  - the box is the bbox padded by marginFactor * diagonal on every side;
 *  - the keep-point is the bbox centre (internal) or a padded-box corner (external).
 */
export function computeDomain(bounds: MeshBounds, config: SnappyConfig): SnappyDomain {
  const diag = diagonal(bounds) || 1;
  const cellSize = config.baseCellSize && config.baseCellSize > 0 ? config.baseCellSize : diag / 40;
  const pad = Math.max(0, config.marginFactor) * diag;

  const boxMin: [number, number, number] = [
    bounds.min[0] - pad,
    bounds.min[1] - pad,
    bounds.min[2] - pad,
  ];
  const boxMax: [number, number, number] = [
    bounds.max[0] + pad,
    bounds.max[1] + pad,
    bounds.max[2] + pad,
  ];
  const counts: [number, number, number] = [
    clampCount((boxMax[0] - boxMin[0]) / cellSize),
    clampCount((boxMax[1] - boxMin[1]) / cellSize),
    clampCount((boxMax[2] - boxMin[2]) / cellSize),
  ];

  const locationInMesh = config.locationInMesh ?? defaultLocationInMesh(bounds, boxMin, config.domainType);

  return { boxMin, boxMax, counts, cellSize, locationInMesh };
}

/**
 * The auto keep-point: the bbox centre for an internal domain (inside the closed
 * surface → snappy keeps the interior), or a corner of the padded box for an
 * external domain (guaranteed outside the surface, since the box extends past the
 * bbox → snappy keeps the exterior). Both are user-overridable in the UI.
 */
function defaultLocationInMesh(
  bounds: MeshBounds,
  boxMin: [number, number, number],
  domainType: DomainType,
): [number, number, number] {
  if (domainType === 'external') {
    // Nudge just inside the box corner so the point is strictly interior to the box.
    const eps = [
      (bounds.min[0] - boxMin[0]) * 0.01,
      (bounds.min[1] - boxMin[1]) * 0.01,
      (bounds.min[2] - boxMin[2]) * 0.01,
    ];
    return [boxMin[0] + eps[0], boxMin[1] + eps[1], boxMin[2] + eps[2]];
  }
  return [
    (bounds.min[0] + bounds.max[0]) / 2,
    (bounds.min[1] + bounds.max[1]) / 2,
    (bounds.min[2] + bounds.max[2]) / 2,
  ];
}

/** Format a number for a dict (avoid scientific-notation surprises, trim noise). */
function fmt(n: number): string {
  if (!Number.isFinite(n)) return '0';
  // Six significant figures is plenty for mesh coordinates and keeps dicts tidy.
  return Number(n.toPrecision(6)).toString();
}

/** controlDict for the mesh utilities (application snappyHexMesh; one time step). */
export function renderMeshingControlDict(): string {
  return `${foamHeader('dictionary', 'controlDict', 'system')}
application     snappyHexMesh;
startFrom       startTime;
startTime       0;
stopAt          endTime;
endTime         1;
deltaT          1;
writeControl    timeStep;
writeInterval   1;
purgeWrite      0;
writeFormat     ascii;
writePrecision  6;
writeCompression off;
timeFormat      general;
timePrecision   6;
runTimeModifiable true;
${FOOTER}`;
}

/** Minimal fvSchemes — enough for blockMesh / snappyHexMesh / checkMesh to load. */
export function renderMeshingFvSchemes(): string {
  return `${foamHeader('dictionary', 'fvSchemes', 'system')}
ddtSchemes          { default steadyState; }
gradSchemes         { default Gauss linear; }
divSchemes          { default none; }
laplacianSchemes    { default Gauss linear corrected; }
interpolationSchemes { default linear; }
snGradSchemes       { default corrected; }
${FOOTER}`;
}

/** Minimal fvSolution — the mesh utilities only need it to exist. */
export function renderMeshingFvSolution(): string {
  return `${foamHeader('dictionary', 'fvSolution', 'system')}
solvers {}

SIMPLE
{
    nNonOrthogonalCorrectors 0;
}
${FOOTER}`;
}

/** blockMeshDict: a single hex background box, sized from the resolved domain. */
export function renderBlockMeshDict(domain: SnappyDomain): string {
  const [x0, y0, z0] = domain.boxMin;
  const [x1, y1, z1] = domain.boxMax;
  const [nx, ny, nz] = domain.counts;
  const v = (x: number, y: number, z: number) => `    (${fmt(x)} ${fmt(y)} ${fmt(z)})`;
  return `${foamHeader('dictionary', 'blockMeshDict', 'system')}
scale 1;

vertices
(
${v(x0, y0, z0)}
${v(x1, y0, z0)}
${v(x1, y1, z0)}
${v(x0, y1, z0)}
${v(x0, y0, z1)}
${v(x1, y0, z1)}
${v(x1, y1, z1)}
${v(x0, y1, z1)}
);

blocks
(
    hex (0 1 2 3 4 5 6 7) (${nx} ${ny} ${nz}) simpleGrading (1 1 1)
);

edges ();

boundary
(
    domainBoundary
    {
        type patch;
        faces
        (
            (0 3 2 1)
            (4 5 6 7)
            (0 1 5 4)
            (2 3 7 6)
            (1 2 6 5)
            (0 4 7 3)
        );
    }
);

mergePatchPairs ();
${FOOTER}`;
}

/** surfaceFeatureExtractDict: one feature-extraction block per STL region. */
export function renderSurfaceFeatureExtractDict(stlNames: string[]): string {
  const blocks = stlNames
    .map(
      (name) => `${name}
{
    extractionMethod    extractFromSurface;
    extractFromSurfaceCoeffs { includedAngle 150; }
    subsetFeatures { nonManifoldEdges no; openEdges yes; }
    writeObj no;
}`,
    )
    .join('\n\n');
  return `${foamHeader('dictionary', 'surfaceFeatureExtractDict', 'system')}
${blocks}
${FOOTER}`;
}

/** snappyHexMeshDict: castellate + snap always, layers optional; one region per STL. */
export function renderSnappyHexMeshDict(
  stlNames: string[],
  domain: SnappyDomain,
  config: SnappyConfig,
): string {
  // `region` is the snappy name (a valid word); `emesh` is the feature file the
  // extractor actually wrote — its basename is the STL stem VERBATIM (hyphens and
  // all), so it must be referenced by the stem, not the sanitized region name.
  const regions = stlNames.map((name) => ({
    file: name,
    region: regionNameFor(name),
    emesh: `${name.replace(/\.[^.]+$/, '')}.eMesh`,
  }));
  const geometry = regions
    .map((r) => `    ${r.file} { type triSurfaceMesh; name ${r.region}; }`)
    .join('\n');
  const features = regions
    .map((r) => `        { file "${r.emesh}"; level ${config.featureLevel}; }`)
    .join('\n');
  const refinementSurfaces = regions
    .map((r) => {
      // Per-surface refinement (keyed by the STL file name) overrides the default.
      const level = config.surfaceRefinements?.[r.file] ?? config.surfaceRefinement;
      return `        ${r.region} { level (${level.min} ${level.max}); }`;
    })
    .join('\n');
  // Layers grow only on the chosen surfaces (the selected boundaries); an omitted
  // or empty list means every surface, so a legacy config still layers all walls.
  const chosen = config.addLayers.surfaces;
  const layerRegions =
    chosen && chosen.length > 0 ? regions.filter((r) => chosen.includes(r.file)) : regions;
  const layers = layerRegions
    .map((r) => `        ${r.region} { nSurfaceLayers ${config.addLayers.nLayers}; }`)
    .join('\n');
  const [lx, ly, lz] = domain.locationInMesh;

  return `${foamHeader('dictionary', 'snappyHexMeshDict', 'system')}
castellatedMesh true;
snap            true;
addLayers       ${config.addLayers.enabled ? 'true' : 'false'};

geometry
{
${geometry}
}

castellatedMeshControls
{
    maxLocalCells       1000000;
    maxGlobalCells      5000000;
    minRefinementCells  10;
    nCellsBetweenLevels 3;
    maxLoadUnbalance    0.10;
    resolveFeatureAngle 30;
    allowFreeStandingZoneFaces true;

    features
    (
${features}
    );

    refinementSurfaces
    {
${refinementSurfaces}
    }

    refinementRegions {}

    locationInMesh (${fmt(lx)} ${fmt(ly)} ${fmt(lz)});
}

snapControls
{
    nSmoothPatch        3;
    tolerance           2.0;
    nSolveIter          30;
    nRelaxIter          5;
    nFeatureSnapIter    10;
    implicitFeatureSnap false;
    explicitFeatureSnap true;
    multiRegionFeatureSnap false;
}

addLayersControls
{
    relativeSizes       ${config.addLayers.relativeSizes ? 'true' : 'false'};
    layers
    {
${layers}
    }
    expansionRatio      ${fmt(config.addLayers.expansionRatio)};
    finalLayerThickness ${fmt(config.addLayers.finalLayerThickness)};
    minThickness        ${fmt(minLayerThickness(config.addLayers))};
    nGrow               0;
    featureAngle        60;
    slipFeatureAngle    30;
    nRelaxIter          3;
    nSmoothSurfaceNormals 1;
    nSmoothNormals      3;
    nSmoothThickness    10;
    maxFaceThicknessRatio 0.5;
    maxThicknessToMedialRatio 0.3;
    minMedialAxisAngle  90;
    nBufferCellsNoExtrude 0;
    nLayerIter          50;
}

meshQualityControls
{
    maxNonOrtho         65;
    maxBoundarySkewness 20;
    maxInternalSkewness 4;
    maxConcave          80;
    minVol              1e-13;
    minTetQuality       1e-15;
    minArea             -1;
    minTwist            0.02;
    minDeterminant      0.001;
    minFaceWeight       0.02;
    minVolRatio         0.01;
    minTriangleTwist    -1;
    nSmoothScale        4;
    errorReduction      0.75;
}

writeFlags ( scalarLevels layerSets layerFields );
mergeTolerance 1e-6;
${FOOTER}`;
}
